### ISSUE TITLE
It would be nice to see the number of reviews and the average review on the home page

### ISSUE THREAD

**Issue by travisvalenti** [thewrongjames/the-anthropocene-reviewed-reviewed#1]
It would be nice to see the number of reviews and/or the average review on the home page, so that we can see at a glance which episodes have more activity and which reviews they are getting on average.

**Comment by thewrongjames** [comment]
Mmm. Unfortunately firebase functions aren't free anymore, and I'm trying to keep this free for now.

**Comment by thewrongjames** [comment]
However, that doesn't mean it isn't possible to do. I could submit an update to that from the client side. Now, obviously, that sounds terrible, but I think I might be able to put it in a transaction with the create of the review, and then validate that the change to the average is correct using firestore security rules. Thereby, hopefully safely, offloading all the computation to the client. Maybe. I'll need to look into it.

**Comment by thewrongjames** [comment]
Looks like this might do it: https://firebase.google.com/docs/firestore/manage-data/transactions#data_validation_for_atomic_operations

Strange way to do valid summaries - make the client do it and then check that they did it right. But, if it works, and it's free, I'll take it.
